name: Model Building And Training Workflow

on:
  push:
    branches: [ @@@GITHUB_REPOSITORY_BRANCH_NAME@@@ ]

jobs:
  model-building-and-training:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Local Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: @@@AWS_REGION@@@

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall . "awscli>1.20.30"

      - name: Trigger Model Building and Training by calling Sagemaker pipeline
        run: |
          run-pipeline --module-name pipelines.abalone.pipeline \
            --role-arn @@@SAGEMAKER_PIPELINE_ROLE_ARN@@@ \
            --tags "[{\"Key\":\"sagemaker:project-name\", \"Value\":\"@@@SAGEMAKER_PROJECT_NAME@@@\"}, {\"Key\":\"sagemaker:project-id\", \"Value\":\"@@@SAGEMAKER_PROJECT_ID@@@\"}]" \
            --kwargs "{\"region\":\"@@@AWS_REGION@@@\",\"sagemaker_project_arn\":\"@@@SAGEMAKER_PROJECT_ARN@@@\",\"role\":\"@@@SAGEMAKER_PIPELINE_ROLE_ARN@@@\",\"default_bucket\":\"@@@ARTIFACT_BUCKET@@@\",\"pipeline_name\":\"@@@SOURCE_MODEL_PACKAGE_GROUP_NAME@@@\",\"model_package_group_name\":\"@@@SOURCE_MODEL_PACKAGE_GROUP_NAME@@@\",\"base_job_prefix\":\"@@@SOURCE_MODEL_PACKAGE_GROUP_NAME@@@\"}"
          echo "Create/Update of the SageMaker Pipeline and execution completed."
        env:
          PYTHONUNBUFFERED: TRUE
